### ISSUE TITLE
Resource scanner dont work anymore

### ISSUE THREAD

**Issue by Cora74** [TheRealBeef/Satisfactory-Resource-Roulette#2]
After last update i started a new game and realised that my scanner can't find anything no more.
I can use it, but it won't show any resources. Even when i stand right in front of them.
I loaded a old save game and got the same problem there. I already used the mod there and since now it didn't make any issue and worked good.
But now, without beeing able to scan after resources, the save isn't playable anymore.
And the i needed to deactivate it for my new game.

**Comment by TheRealBeef** [comment]
I don't think this should be happening - can you send the save file (either here on Github or @iamtherealbeef on the Satisfactory Modding Discord, you can DM me or in the Help-using-mods forum if you prefer) so I can see what's going on?

**Comment by Cora74** [comment]
[Cora's Beach_autosave_2.zip](https://github.com/user-attachments/files/17991696/Cora.s.Beach_autosave_2.zip)
 Sure, here is myy old save where the scanner stopped working. The new game i already deleted. 
But i have a lot mods installed. Anyway, after deactivating your mod i had no issue anymore.
Hope you can find out the problem, cause randomising the resources is a great idea to completly change the game.

**Comment by TheRealBeef** [comment]
I see two potential problems:

First, did you update from version 1.0.0-1.0.3, or was your initial version 1.1.0 and you updated to the current 1.1.2?

1.1.0 introduced new metadata that's not in the earlier versions and seems to be missing from the save file. It's why 1.1.0 required a new save. I cannot either update or re-roll nodes in your save file as well, as this metadata is missing. However, Resource Roulette stores its state regardless of this metadata, which is why it still mostly works, and it isn't the cause of the pinging issues.

The issues with the pings is most probably a mod conflict, as starting your game world with a large number of mods missing I don't have issues getting resource nodes to ping. 

![Untitled](https://github.com/user-attachments/assets/ccb259ac-db09-431e-9a51-3cf3cbe9b6d0)

One of these below is likely the culprit. I will try to look into this over the weekend

[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: 41 missing mods found:
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: Better Grass is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: Blood Moon is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: Blueprint Designer Plus is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: CBuildings is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: CommunityBasicTracks is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: CommunityRailwaySet is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: CommunityRoadNetwork is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: ContainerScreen is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: Decoration is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: DI_More_Lights is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: DI_MoreGlassAndWalls is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: DoorsAnywhere is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: Early & Free Blueprint Designer is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: EarlyMapRedux is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: FileSystemLibrary is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: FixClientResourceSinkPoints is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: FlexSplines is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: GhostConstruction is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: MoreDecorations is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: MoreMilestones_2 is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: PaintGunMK2 is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: People is missing
[2024.12.03-14.05.15:859][593]LogSatisfactoryModLoader: Warning: RailNetwork is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: RoadSplineTool is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: SatelliteLink is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: ShowEnemiesHealth is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: SilentArtifacts is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: SmallStorage is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: SnapOn is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: SpecialContainers is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: SpySat is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: TFIT - The Ficsit Information Tool is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: ThirdPersonView is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: UndoZ is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: UpsideDownFoundations is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: Vertical Logistics is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: VerticalSplitter is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: Wagons is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: Wall Conveyor Supports is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: WallHoleConveyor is missing
[2024.12.03-14.05.15:860][593]LogSatisfactoryModLoader: Warning: X3 Lights is missing

**Comment by Cora74** [comment]
First I want to thank you for this nice support.

I needed to install satisfactory new last week.
So, I have the new 1.1.0 version installed.
You say I am missing the old metadata files now?

I understand. And I see that it seems to work in your game.
But none of the other mods do anything to the resource nodes or the scaner.
Anyway, I looks like this issue is not from your mods alone.

In my test the scaner worked a few times, but after i used the refresh of your mod, it stopped.
I will test it with my old save again tomorrow. This time without using the refresh function to see if the issue comes from there.

If I load this mod in a save game I played without, this mod wont do anything without using the refresh function, or am i wrong?

**Comment by TheRealBeef** [comment]
If you had a game with the 1.0.x version installed, it did not save any of the original node distribution data and some properties about the world purity counts and so on (what i mean by metadata) and updating to the 1.1.x version with the same save doesn't fix it. I had to do a bit of restructuring between these versions and I found I needed to cache that metadata. This data is impossible to separate between the mod data and vanilla game data in the old version when it has its own information in the save as well, so it isn't possible to make pseudorandom distributions that will be the same every time for every seed and mod list (which is needed for multiplayer). I think I worded this very poorly but simple version is that it's not possible to update between 1.0.x to 1.1.x within the same save file.

However, if you installed the 1.1.x version initially, then for some reason it didn't save this metadata about the world properly and this is something I need to look into more.

The only need to use the "update" button currently is if you started with the 1.1.0 version as I improved the settling for resource nodes between 1.1.0 and 1.1.1. Since they are settled only one time as you get near to them for the first time in a save and then this position is cached (to give better performance), it gives a way to allow them to re-settle using the improved logic. It also fixes a problem I had with some lone nodes being incorrect type due to not re-initializing a pseudorandomization variable when using the "re-roll" button, which meant that the node distribution wasn't exactly what the seed should have given. This was important to fix so that multiplayer works properly. 

All of this said however, using the "update" button will not break anything and you should be able to press it all you like.

The only way to theoretically fix it is to load and then save the game without the mod installed, then re-enable the 1.1.x version and start that save. This way it purges all information from the 1.0.x version. However, if you have miners, portable miners, or crude oil extractors on resource nodes this can cause a crash as the vanilla game doesn't have a way to handle the changed node type (from randomized back to vanilla) on load, but my mod does. This is probably a good feature to add though (a button to destroy all these miners before removing the mod to make it easier)

If you load this mod in a save game you played without, it will run its checks, cache the data, and randomize the nodes without using the refresh function.

**Comment by TheRealBeef** [comment]
I notice in the save file that you sent, that if I use either the re-roll or the update buttons, that all the nodes disappear and in the log file it says there are no nodes available for spawning. This happens because there is not the original node distribution data saved into the savefile for my mod to use to recreate the randomization.

I will test it as well to see if there's an easier way, but in the next day or two I will try to put a button into the session settings at the bottom that preps the savefile for removal of the mod and prevents potential crashes, so that this process will be easier.

**Comment by Cora74** [comment]
I tested this savegame and in a save i never used your mod.
When I load the savegame everything is fine until I push the update button. Then all nodes dissapear.
I thougth this button would change the nodes, but now I understand that its just for updating to a never version.
But when i try to load that save without your mod I got a CTD (crash to desktop).
In a new game I got a CTD while pushing the update button. But I had some mobile miners somewhere. I guess it crashed cause of them.

I thougth the update button would update the nodes, not the mod. My mistake.
Still dont get how this mod works.
So, I do not really need that button to change my nodes, even when i started the game without your mod?
And your mod will change the nodes when get loaded the first time i used it in a savegame?
Or just when i get close to a node? And when, how to find nodes with the scaner when they will hange in the moment i get close to them?

Problem is that I wanna change the settings. Dont wanna randomize SAM nodes, for example.
I was sure that I need to update it after changing the settings. But using the update button leads to losing everything and using reroll will crash my game, cause there are already miners on a lot of nods.
But I could see, that the nods are already randomized, cause i found sulfur in a place where i dont have it in another game.

Anyway, I dont wanna run all 5 nodes into a new SAM node, but i do when using the mod and can only change the options AFTER the mod already randomized all nodes. And my oil is not grouped either.

When I load a save game I never used your mod, and then I start it with your mod, will every node change then?
And after I changed the settings, do I need to use the update or reroll button or will it work with the new settings, even that I made them after they changed the nodes?
And will it destroy my production lines, cause they wont gather the right resource anymore?

Sorry for asking silly questions, but when I use the mod, I dont wanna find out after days that all my afford was for nothing, cause the save is broken.

**Comment by TheRealBeef** [comment]
> When I load the savegame everything is fine until I push the update button. Then all nodes dissapear.

This is definitely not intended behavior, so I guess it is the mod conflict

> But when i try to load that save without your mod I got a CTD (crash to desktop)

This is that miner/portable miner and changing nodes types situation I mentioned previously, will add a button to make it possible to remove mod

> Still dont get how this mod works.

When you start a new game, there is a menu to set savegame settings, you can set it here.
![image](https://github.com/user-attachments/assets/9288b9c3-7309-43a5-9bfa-70533d80cf21)
Alternatively, you should have no issues to adjust the node settings and use the re-roll button either.
I will give some better explanations/names to the buttons to try and improve understanding, as it's clear these buttons aren't very clear what they do. I will move the update button to separate place at the bottom. If you have miners on nodes and use the update or re-roll button, it should have no issues when re-rolling as the mod handles it. I do think it will crash on the old save as it doesn't spawn miners.

> When I load a save game I never used your mod, and then I start it with your mod, will every node change then?

Yes

> And after I changed the settings, do I need to use the update or reroll button or will it work with the new settings, even that I made them after they changed the nodes?

After you change settings in a save, click apply and then click the re-roll button. I will make this more clear.

**Comment by TheRealBeef** [comment]
I've updated Resource Roulette to version 1.1.3, and it should be available in a few minutes.
This adds a button at the bottom under Admin Options to prep the savegame for mod removal

To fix Cora's Beach, do the following
1. Load the savegame with current version of Resource Roulette added
2. Open the mod savegame settings with the game loaded, and click the "Click to Prep Savegame for Mod Removal" button. This removes all vanilla extractors on custom nodes
3. Save the game
4. Remove the Resource Roulette Mod from the Mod Loader, or at least deactivate it
5. Load the game again (now that you are without Resource Roulette)
6. Save the game. This save now has all Resource Roulette data removed from the save.
7. Re-enable Resource Roulette in the mod loader
8. When you load the game, it should be repaired and function properly.

**Comment by Cora74** [comment]
Many thanks for that great explanation. It worked to get the mod away from save. And all nods are like in vanilla game.
After i readded the mod, it worked for a few seconds, but then i got an CTD without doing anything.
I was not able to test the scaner before it crashed.
I will add the crash report. Not sure why it crashed, your mod was the only thing I changed.

But i can use the save again just with all nodes like in vanilla game. I am just happy to not loose that save. 
Thanks. For me the issue is solved and can be closed.

But I am still here to help with testing cause of that CDT. Here is the crashreport:
![Screenshot 2024-12-05 161902](https://github.com/user-attachments/assets/5757c896-8071-4907-a8cc-78392f2fe5d8)

**Comment by TheRealBeef** [comment]
That crash from the limited information in the screenshot is related to the conveyor item subsystem ... which my mod doesn't touch so I'm unsure how I'd even address this.

It's likely a mod conflict ultimately with one of the other mods is my best guess. I'm glad that you were able to save the save though.

**Comment by Cora74** [comment]
Its possible hat this crash came from SnapOn. Cause there was an Update with SnapOn and this mod change something to conveyor belts and splitter and merger. Yesterday i got this crash even without your mod.
But today there was an update to SnapOn.
However the crash did not repeat and now everything works fine.
I can still change the nods with reroll, and my occupied nodes stay like they are, but others change.
Perfect. Many thanks for helping.
